source "https://rubygems.org"

ruby "3.4.8"

# Core Rails gems
gem "rails", "~> 7.1.6"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"

# Authentication & Security
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 3.1"
gem "rack-cors"
gem "rack-attack"

# Background Jobs
gem "sidekiq", "~> 7.3"
gem "redis", ">= 4.0.1"
gem 'connection_pool', '~> 2.4'

# JSON Serialization
gem "alba", "~> 3.3"

# AWS SDK (for S3 uploads later)
gem "aws-sdk-s3", "~> 1.0", require: false

# Reduces boot times through caching
gem "bootsnap", require: false

# Pagination
gem "kaminari", "~> 1.2"

# Use Active Storage variants
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
  
  # Testing
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  
  # Environment variables
  gem "dotenv-rails"
  
  # Interactive console
  gem "pry-rails"

  gem 'simplecov', require: false, group: :test
end

group :development do
  # Code quality
  gem "rubocop-rails", require: false
  gem "annotate"
  gem "bullet"
end

group :test do
  gem "shoulda-matchers", "~> 5.0"
  gem "database_cleaner-active_record"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]